// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  image: dynamic(() => import("./Image")),
  text: dynamic(() => import("./Text")),
  video: dynamic(() => import("./Video")),
};
